# Generated by Django 6.0 on 2025-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر / ترجیح نمی\u200cدهم بگویم')], max_length=1, verbose_name='جنسیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
        ),
    ]
