# Generated by Django 5.2.7 on 2026-08-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('NONE', 'هرگز مصرف نکرده\u200cام'), ('PAST', 'در گذشته مصرف می\u200cکردم (فعلاً خیر)'), ('OCCASIONAL', 'گاه\u200cبه\u200cگاه مصرف می\u200cکنم'), ('REGULAR', 'مصرف منظم دارم')], max_length=12, null=True, verbose_name='مصرف الکل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='caffeine',
            field=models.CharField(blank=True, choices=[('NONE', 'اصلاً مصرف نمی\u200cکنم'), ('LOW', 'کم (۱ فنجان یا کمتر در روز)'), ('MODERATE', 'متوسط (۲–۳ فنجان در روز)'), ('HIGH', 'زیاد (بیش از ۳ فنجان در روز)')], max_length=10, null=True, verbose_name='مصرف کافئین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, choices=[('NONE', 'بدون تحصیلات رسمی'), ('PRIMARY', 'ابتدایی'), ('SECONDARY', 'متوسطه'), ('DIPLOMA', 'دیپلم'), ('ASSOCIATE', 'کاردانی'), ('BACHELOR', 'کارشناسی'), ('MASTER', 'کارشناسی ارشد'), ('PHD', 'دکتری')], max_length=20, null=True, verbose_name='سطح تحصیلات'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marriage',
            field=models.CharField(blank=True, choices=[('S', 'مجرد'), ('M', 'متاهل')], max_length=1, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mental_disorders',
            field=models.JSONField(blank=True, default=list, help_text='می\u200cتوانید چند مورد را انتخاب کنید', verbose_name='اختلالات روانی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seizure',
            field=models.CharField(blank=True, choices=[('NONE', 'ندارم'), ('PAST', 'در گذشته داشتم (فعلاً خیر)'), ('CONTROLLED', 'دارم ولی تحت کنترل است'), ('ACTIVE', 'دارم و فعال است')], max_length=12, null=True, verbose_name='سابقه تشنج یا صرع'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sleep',
            field=models.CharField(blank=True, choices=[('NONE', 'ندارم'), ('INSOMNIA', 'بی\u200cخوابی'), ('HYPERSOMNIA', 'خواب\u200cآلودگی بیش از حد'), ('SLEEP_APNEA', 'آپنه خواب'), ('NIGHTMARE', 'کابوس\u200cهای مکرر'), ('OTHER', 'سایر اختلالات خواب')], max_length=15, null=True, verbose_name='اختلال خواب'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='میانگین ساعات خواب'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smoking',
            field=models.CharField(blank=True, choices=[('NONE', 'هرگز مصرف نکرده\u200cام'), ('PAST', 'در گذشته مصرف می\u200cکردم (فعلاً خیر)'), ('OCCASIONAL', 'گاه\u200cبه\u200cگاه مصرف می\u200cکنم'), ('REGULAR', 'مصرف منظم دارم')], max_length=12, null=True, verbose_name='مصرف سیگار'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='substance',
            field=models.CharField(blank=True, choices=[('NONE', 'هرگز مصرف نکرده\u200cام'), ('PAST', 'در گذشته مصرف کرده\u200cام (فعلاً خیر)'), ('OCCASIONAL', 'گاه\u200cبه\u200cگاه مصرف می\u200cکنم'), ('REGULAR', 'مصرف منظم دارم')], max_length=12, null=True, verbose_name='مصرف مواد مخدر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='supplement',
            field=models.CharField(blank=True, choices=[('NONE', 'مصرف نمی\u200cکنم'), ('OCCASIONAL', 'گاه\u200cبه\u200cگاه'), ('REGULAR', 'به\u200cصورت منظم')], max_length=12, null=True, verbose_name='مصرف مکمل\u200cها یا ویتامین\u200cها'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tbi',
            field=models.CharField(blank=True, choices=[('NONE', 'ندارم'), ('MILD', 'ضربه خفیف (بدون از دست دادن هوشیاری)'), ('MODERATE', 'ضربه متوسط (از دست دادن کوتاه\u200cمدت هوشیاری)'), ('SEVERE', 'ضربه شدید (از دست دادن طولانی\u200cمدت هوشیاری یا بستری)')], max_length=10, null=True, verbose_name='سابقه ضربه مغزی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trauma',
            field=models.CharField(blank=True, choices=[('NONE', 'ندارم'), ('MILD', 'رویداد استرس\u200cزای خفیف'), ('MODERATE', 'رویداد استرس\u200cزای متوسط'), ('SEVERE', 'ترومای شدید یا چندین رویداد')], max_length=10, null=True, verbose_name='سابقه تروما یا رویدادهای استرس\u200cزا'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hand',
            field=models.CharField(blank=True, choices=[('R', 'راست'), ('L', 'چپ')], max_length=1, null=True, verbose_name='دست غالب'),
        ),
    ]
