# Generated by Django 6.0 on 2025-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
