# Generated by Django 5.2.7 on 2026-08-08 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_alcohol_customuser_caffeine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmsequencepracticeresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-2)تمرین تشخیص توالی'},
        ),
        migrations.AlterModelOptions(
            name='pcmvalencepracticeresponse',
            options={'ordering': ['trial'], 'verbose_name': 'B-1)تمرین رتبه\u200cبندی خوشایندی'},
        ),
        migrations.CreateModel(
            name='VolumeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='volume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حجم صدا',
                'verbose_name_plural': 'حجم صدا',
                'ordering': ['-created_at'],
            },
        ),
    ]
