# Generated by Django 5.2.7 on 2026-01-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ratingresponse_stimulus_pcmresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcmresponse',
            name='practice_correct',
        ),
        migrations.RemoveField(
            model_name='pcmresponse',
            name='practice_response',
        ),
        migrations.AddField(
            model_name='pcmresponse',
            name='is_consistent',
            field=models.BooleanField(default=True, verbose_name='آیا توالی ارائه\u200cشده با کیو سازگار بود؟'),
        ),
        migrations.AlterField(
            model_name='pcmresponse',
            name='category_stim1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک اول'),
        ),
        migrations.AlterField(
            model_name='pcmresponse',
            name='category_stim2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک دوم'),
        ),
        migrations.AlterField(
            model_name='pcmresponse',
            name='expected_sequence',
            field=models.CharField(blank=True, choices=[('Neutral-Neutral', 'خنثی → خنثی'), ('Negative-Neutral', 'منفی → خنثی'), ('Neutral-Negative', 'خنثی → منفی')], max_length=30, null=True, verbose_name='توالی مورد انتظار (مثل Neutral-Neutral)'),
        ),
        migrations.CreateModel(
            name='PCMPracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(verbose_name='شماره تریال')),
                ('cue', models.CharField(max_length=100, verbose_name='نام فایل کیو (Cue)')),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک اول')),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک دوم')),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک اول')),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک دوم')),
                ('practice_response', models.CharField(blank=True, max_length=20, null=True, verbose_name='پاسخ کاربر در مرحله آزمایشی (کدام توالی؟)')),
                ('practice_correct', models.BooleanField(blank=True, null=True, verbose_name='آیا پاسخ آزمایشی correct بوده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ مرحله آزمایشی',
                'verbose_name_plural': 'پاسخ مرحله آزمایشی',
                'ordering': ['-created_at'],
            },
        ),
    ]
