# Generated by Django 5.2.7 on 2026-08-08 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pcmsequencepracticeresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='block',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره بلاک'),
        ),
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='expected_sequence',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='توالی مورد انتظار'),
        ),
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='is_consistent',
            field=models.BooleanField(default=True, verbose_name='آیا توالی ارائه\u200cشده با کیو سازگار بود؟'),
        ),
        migrations.CreateModel(
            name='PCMSequenceCatchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره بلاک')),
                ('trial', models.PositiveIntegerField()),
                ('cue', models.CharField(max_length=100)),
                ('user_response', models.CharField(blank=True, max_length=30, null=True)),
                ('response_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('delay_number', models.PositiveIntegerField(blank=True, default=0)),
                ('response_input_method', models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B-2)Catch',
                'ordering': ['created_at'],
                'unique_together': {('user', 'trial', 'created_at')},
            },
        ),
    ]
