# Generated by Django 5.2.7 on 2026-01-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pcmresponse_practice_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmpracticeresponse',
            name='practice_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='pcmpracticeresponse',
            name='practice_response',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='توالی انتخابی'),
        ),
    ]
