# Generated by Django 5.2.7 on 2026-01-04 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pcmpracticeresponse_practice_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCMReRatingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus_file', models.CharField(max_length=200, verbose_name='نام فایل محرک (مثل 5-MP-MA/102.WAV)')),
                ('stimulus_number', models.CharField(max_length=50, verbose_name='شماره محرک (مثل 102)')),
                ('valence', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='خوشایندی (Valence)')),
                ('valence_rt', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی (میلی\u200cثانیه)')),
                ('arousal', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='برانگیختگی (Arousal)')),
                ('arousal_rt', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ برانگیختگی (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رتبه\u200cبندی مجدد محرک PCM',
                'verbose_name_plural': 'رتبه\u200cبندی\u200cهای مجدد محرک\u200cهای PCM',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'stimulus_number')},
            },
        ),
    ]
