# Generated by Django 5.2.7 on 2026-08-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pcmsequencepracticeresponse_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmcatchresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-4)PCM-Catch'},
        ),
        migrations.AlterModelOptions(
            name='pcmmainresponse',
            options={'ordering': ['-created_at', 'block', 'trial'], 'verbose_name': 'B-5)PCM-Main', 'verbose_name_plural': 'B-5)PCM-Main'},
        ),
        migrations.AlterModelOptions(
            name='pcmsequencecatchresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-3)SequenceCatch'},
        ),
        migrations.AlterModelOptions(
            name='pcmsequencepracticeresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-2)SequencePractice'},
        ),
        migrations.AlterModelOptions(
            name='pcmvalencepracticeresponse',
            options={'ordering': ['trial'], 'verbose_name': 'B-1)ValencePractice'},
        ),
        migrations.AlterModelOptions(
            name='ratingmainresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'B-7)Rating'},
        ),
        migrations.AlterModelOptions(
            name='ratingpracticeresponse',
            options={'ordering': ['trial'], 'verbose_name': 'B-6)RatingPractice'},
        ),
    ]
