# Generated by Django 5.2.7 on 2026-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pcmreratingresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmresponse',
            name='expected_sequence',
            field=models.CharField(blank=True, choices=[('Neutral-Neutral', 'Neutral-Neutral'), ('Negative-Neutral', 'Negative-Neutral'), ('Neutral-Negative', 'Neutral-Negative')], max_length=30, null=True, verbose_name='توالی مورد انتظار'),
        ),
    ]
