# Generated by Django 5.2.7 on 2026-01-04 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pcmresponse_expected_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmpracticeresponse',
            options={'ordering': ['-created_at'], 'verbose_name': '1-PCM-practice', 'verbose_name_plural': '1-PCM-practice'},
        ),
        migrations.AlterModelOptions(
            name='pcmreratingresponse',
            options={'ordering': ['-created_at'], 'verbose_name': '3-PCM-rating', 'verbose_name_plural': '3-PCM-rating'},
        ),
        migrations.AlterModelOptions(
            name='pcmresponse',
            options={'ordering': ['-created_at', 'block', 'trial'], 'verbose_name': '2-PCM-main', 'verbose_name_plural': '2-PCM-main'},
        ),
        migrations.AlterModelOptions(
            name='ratingresponse',
            options={'ordering': ['-created_at'], 'verbose_name': '0-Rating', 'verbose_name_plural': '0-Rating'},
        ),
        migrations.CreateModel(
            name='PCMValencePracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(verbose_name='شماره تریال تمرینی رتبه\u200cبندی')),
                ('cue', models.CharField(max_length=100, verbose_name='کیو')),
                ('stimulus1', models.CharField(max_length=100, verbose_name='محرک اول')),
                ('stimulus2', models.CharField(max_length=100, verbose_name='محرک دوم')),
                ('valence_stim1', models.IntegerField(blank=True, null=True)),
                ('valence_rt_stim1', models.PositiveIntegerField(blank=True, null=True)),
                ('valence_stim2', models.IntegerField(blank=True, null=True)),
                ('valence_rt_stim2', models.PositiveIntegerField(blank=True, null=True)),
                ('valence_sequence', models.IntegerField(blank=True, null=True)),
                ('valence_rt_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تمرینی رتبه\u200cبندی خوشایندی',
                'verbose_name_plural': 'تمرینی رتبه\u200cبندی خوشایندی',
                'unique_together': {('user', 'trial')},
            },
        ),
    ]
