# Generated by Django 5.2.7 on 2026-01-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pcmpracticeresponse_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCMValencePracticeResponse',
        ),
    ]
