# Generated by Django 5.2.7 on 2026-01-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_pcmvalencepracticeresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCMPreparationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(verbose_name='شماره تریال')),
                ('cue', models.CharField(max_length=100, verbose_name='نام فایل کیو (Cue)')),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک اول')),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک دوم')),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک اول')),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک دوم')),
                ('valence_stim1', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی محرک اول (Valence)')),
                ('valence_rt_stim1', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی محرک اول (میلی\u200cثانیه)')),
                ('valence_stim2', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی محرک دوم (Valence)')),
                ('valence_rt_stim2', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی محرک دوم (میلی\u200cثانیه)')),
                ('valence_sequence', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی کل توالی (Valence)')),
                ('valence_rt_sequence', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی کل توالی (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '2-PCM-Preparation',
                'verbose_name_plural': '2-PCM-Preparation',
                'ordering': ['-created_at', 'trial'],
                'unique_together': {('user', 'trial')},
            },
        ),
    ]
