# Generated by Django 5.2.7 on 2026-01-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pcmpreparationresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pcmpreparationresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pcmpreparationresponse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pcmreratingresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pcmreratingresponse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pcmresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pcmresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='PCMPracticeResponse',
        ),
        migrations.DeleteModel(
            name='PCMPreparationResponse',
        ),
        migrations.DeleteModel(
            name='PCMReRatingResponse',
        ),
        migrations.DeleteModel(
            name='PCMResponse',
        ),
    ]
