# Generated by Django 5.2.7 on 2026-01-05 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pcmpreparationresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCMMainResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveIntegerField(verbose_name='شماره بلاک')),
                ('trial', models.PositiveIntegerField(verbose_name='شماره تریال')),
                ('cue', models.CharField(max_length=100, verbose_name='نام فایل کیو (Cue)')),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک اول')),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فایل محرک دوم')),
                ('expected_sequence', models.CharField(blank=True, choices=[('Neutral-Neutral', 'Neutral-Neutral'), ('Negative-Neutral', 'Negative-Neutral'), ('Neutral-Negative', 'Neutral-Negative')], max_length=30, null=True, verbose_name='توالی مورد انتظار')),
                ('is_consistent', models.BooleanField(default=True, verbose_name='آیا توالی ارائه\u200cشده با کیو سازگار بود؟')),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک اول')),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True, verbose_name='دسته محرک دوم')),
                ('valence_stim1', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی محرک اول (Valence)')),
                ('valence_rt_stim1', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی محرک اول (میلی\u200cثانیه)')),
                ('valence_stim2', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی محرک دوم (Valence)')),
                ('valence_rt_stim2', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی محرک دوم (میلی\u200cثانیه)')),
                ('valence_sequence', models.IntegerField(blank=True, null=True, verbose_name='پاسخ خوشایندی کل توالی (Valence)')),
                ('valence_rt_sequence', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ خوشایندی کل توالی (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '2-PCM-main',
                'verbose_name_plural': '2-PCM-main',
                'ordering': ['-created_at', 'block', 'trial'],
                'unique_together': {('user', 'block', 'trial')},
            },
        ),
        migrations.CreateModel(
            name='PCMSequencePracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('cue', models.CharField(max_length=100)),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True)),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True)),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True)),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True)),
                ('user_response', models.CharField(blank=True, max_length=30, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1-تمرین تشخیص توالی',
                'ordering': ['trial'],
                'unique_together': {('user', 'trial')},
            },
        ),
        migrations.CreateModel(
            name='PCMValencePracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('cue', models.CharField(max_length=100)),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True)),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True)),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True)),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True)),
                ('valence_stim1', models.IntegerField(blank=True, null=True)),
                ('valence_rt_stim1', models.PositiveIntegerField(blank=True, null=True)),
                ('valence_stim2', models.IntegerField(blank=True, null=True)),
                ('valence_rt_stim2', models.PositiveIntegerField(blank=True, null=True)),
                ('valence_sequence', models.IntegerField(blank=True, null=True)),
                ('valence_rt_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2-تمرین رتبه\u200cبندی خوشایندی',
                'ordering': ['trial'],
                'unique_together': {('user', 'trial')},
            },
        ),
        migrations.CreateModel(
            name='RatingMainResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus_file', models.CharField(max_length=200)),
                ('stimulus_number', models.CharField(max_length=50)),
                ('valence', models.IntegerField(blank=True, null=True)),
                ('valence_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('arousal', models.IntegerField(blank=True, null=True)),
                ('arousal_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5-رتبه\u200cبندی اصلی',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'stimulus_number')},
            },
        ),
        migrations.CreateModel(
            name='RatingPracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('stimulus', models.CharField(max_length=100)),
                ('valence', models.IntegerField(blank=True, null=True)),
                ('valence_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('arousal', models.IntegerField(blank=True, null=True)),
                ('arousal_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '4-تمرین رتبه\u200cبندی (Valence+Arousal)',
                'ordering': ['trial'],
                'unique_together': {('user', 'trial')},
            },
        ),
    ]
