# Generated by Django 5.2.7 on 2026-01-06 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pcmmainresponse_pcmsequencepracticeresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCMCueMapping',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mapping', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نگاشت ثابت Cue به Sequence در PCM',
            },
        ),
    ]
