# Generated by Django 5.2.7 on 2026-01-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pcmcuemapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pcmsequencepracticeresponse',
            unique_together={('user', 'trial', 'created_at')},
        ),
    ]
