# Generated by Django 5.2.7 on 2026-01-07 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pcmsequencepracticeresponse_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmmainresponse',
            options={'ordering': ['-created_at', 'block', 'trial'], 'verbose_name': '3-PCM-main', 'verbose_name_plural': '3-PCM-main'},
        ),
        migrations.AlterModelOptions(
            name='pcmsequencepracticeresponse',
            options={'ordering': ['created_at'], 'verbose_name': '1-تمرین تشخیص توالی'},
        ),
        migrations.CreateModel(
            name='PCMCatchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('cue', models.CharField(max_length=100)),
                ('stimulus1', models.CharField(blank=True, max_length=100, null=True)),
                ('stimulus2', models.CharField(blank=True, max_length=100, null=True)),
                ('category_stim1', models.CharField(blank=True, max_length=10, null=True)),
                ('category_stim2', models.CharField(blank=True, max_length=10, null=True)),
                ('user_response', models.CharField(blank=True, max_length=30, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1-تمرین تشخیص توالی',
                'ordering': ['created_at'],
                'unique_together': {('user', 'trial', 'created_at')},
            },
        ),
    ]
