# Generated by Django 5.2.7 on 2026-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pcmmainresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmcatchresponse',
            options={'ordering': ['created_at'], 'verbose_name': '3-PCM-Catch'},
        ),
        migrations.AlterModelOptions(
            name='pcmmainresponse',
            options={'ordering': ['-created_at', 'block', 'trial'], 'verbose_name': '3-PCM-Main', 'verbose_name_plural': '3-PCM-Main'},
        ),
        migrations.AddField(
            model_name='pcmcatchresponse',
            name='block',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره بلاک'),
        ),
    ]
