# Generated by Django 5.2.7 on 2026-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pcmcatchresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmmainresponse',
            name='expected_sequence',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='توالی مورد انتظار'),
        ),
    ]
