# Generated by Django 5.2.7 on 2026-01-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pcmmainresponse_expected_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmainresponse',
            name='trial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
