# Generated by Django 5.2.7 on 2026-01-08 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ratingmainresponse_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingresponse',
            name='trial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RatingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('stimulus', models.CharField(max_length=100)),
                ('valence', models.IntegerField(blank=True, null=True)),
                ('valence_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('arousal', models.IntegerField(blank=True, null=True)),
                ('arousal_rt', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تمرین 0-Rating ',
                'ordering': ['trial'],
                'unique_together': {('user', 'trial')},
            },
        ),
    ]
