# Generated by Django 5.2.7 on 2026-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ratingresponse_trial_ratingpractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingresponse',
            name='stimulus_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
