# Generated by Django 5.2.7 on 2026-07-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ratingresponse_stimulus_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcmcatchresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-3)PCM-Catch'},
        ),
        migrations.AlterModelOptions(
            name='pcmmainresponse',
            options={'ordering': ['-created_at', 'block', 'trial'], 'verbose_name': 'B-3)PCM-Main', 'verbose_name_plural': 'B-3)PCM-Main'},
        ),
        migrations.AlterModelOptions(
            name='pcmsequencepracticeresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'B-1)تمرین تشخیص توالی'},
        ),
        migrations.AlterModelOptions(
            name='pcmvalencepracticeresponse',
            options={'ordering': ['trial'], 'verbose_name': 'B-2)تمرین رتبه\u200cبندی خوشایندی'},
        ),
        migrations.AlterModelOptions(
            name='ratingmainresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'B-5)رتبه\u200cبندی اصلی'},
        ),
        migrations.AlterModelOptions(
            name='ratingpractice',
            options={'ordering': ['trial'], 'verbose_name': 'A-0)practice'},
        ),
        migrations.AlterModelOptions(
            name='ratingpracticeresponse',
            options={'ordering': ['trial'], 'verbose_name': 'B-4)تمرین رتبه\u200cبندی (Valence+Arousal)'},
        ),
        migrations.AlterModelOptions(
            name='ratingresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'A-1)Rating', 'verbose_name_plural': 'A-1)Rating'},
        ),
        migrations.RemoveField(
            model_name='pcmcatchresponse',
            name='category_stim1',
        ),
        migrations.RemoveField(
            model_name='pcmcatchresponse',
            name='category_stim2',
        ),
        migrations.RemoveField(
            model_name='pcmcatchresponse',
            name='stimulus1',
        ),
        migrations.RemoveField(
            model_name='pcmcatchresponse',
            name='stimulus2',
        ),
    ]
