# Generated by Django 5.2.7 on 2026-08-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_pcmcatchresponse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50, verbose_name='مرحله')),
                ('device_type', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=30)),
                ('browser', models.CharField(max_length=30)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='طول صفحه')),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع صفحه')),
                ('is_touch', models.BooleanField(default=False, verbose_name='دستگاه لمسی؟')),
                ('audio_volume', models.FloatField(blank=True, null=True, verbose_name='حجم صدای تنظیم\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ تغییر دستگاه',
                'verbose_name_plural': 'لاگ\u200cهای تغییر دستگاه',
                'ordering': ['-created_at'],
            },
        ),
    ]
