# Generated by Django 5.2.7 on 2026-08-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmcatchresponse',
            name='response_rt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='response_rt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
