# Generated by Django 5.2.7 on 2026-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pcmcatchresponse_response_rt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmcatchresponse',
            name='delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_delay_number_sequence',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_delay_number_stim1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_delay_number_stim2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_delay_number_sequence',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_delay_number_stim1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_delay_number_stim2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingmainresponse',
            name='arousal_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingmainresponse',
            name='valence_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingpractice',
            name='delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingpracticeresponse',
            name='arousal_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingpracticeresponse',
            name='valence_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='arousal_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='valence_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
