# Generated by Django 5.2.7 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pcmcatchresponse_is_active_pcmmainresponse_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingpractice',
            old_name='delay_number',
            new_name='arousal_delay_number',
        ),
        migrations.AddField(
            model_name='ratingpractice',
            name='valence_delay_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
