# Generated by Django 5.2.7 on 2026-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_delay_number_ratingpractice_arousal_delay_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingpractice',
            name='arousal_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingpractice',
            name='valence_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
    ]
