# Generated by Django 5.2.7 on 2026-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ratingpractice_arousal_input_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmcatchresponse',
            name='response_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_input_method_stim1',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_input_method_stim2',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmsequencepracticeresponse',
            name='response_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_input_method_stim1',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_input_method_stim2',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingmainresponse',
            name='arousal_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingmainresponse',
            name='valence_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingpracticeresponse',
            name='arousal_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingpracticeresponse',
            name='valence_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='arousal_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='valence_input_method',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
    ]
