# Generated by Django 5.2.7 on 2026-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pcmcatchresponse_response_input_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmmainresponse',
            name='valence_input_method_sequence',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pcmvalencepracticeresponse',
            name='valence_input_method_sequence',
            field=models.CharField(blank=True, choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('touch', 'Touch')], max_length=20, null=True),
        ),
    ]
